// src/slices/CenteredText.tsx
import * as React from 'react'
import { graphql } from 'gatsby'
import clsx from 'clsx'

import { BoundedBox } from '../components/BoundedBox'
import { HTMLContent } from '../components/HTMLContent'
import type { SliceComponentProps } from '@prismicio/react'

type Slice = Queries.CenteredTextFragment & {
	slice_type: 'centered_text'
}
type Props = SliceComponentProps<Slice>

const CenteredText = ({ slice }: Props) => {
	const textHTML = slice.primary.text.html

	return (
		<BoundedBox
			as="section"
			data-page-centered-text
			className={clsx('relative bg-white', 'py-10 lg:py-20')}
		>
			{textHTML && (
				<HTMLContent
					html={textHTML}
					variant="centeredText"
					className="max-w-2xl mx-auto text-center"
				/>
			)}
		</BoundedBox>
	)
}

export default CenteredText

export const fragment = graphql`
	fragment CenteredText on PrismicPageDataBodyCenteredText {
		id
		primary {
			text {
				html
			}
		}
	}
`

// src/lib/slices/CenteredText/index.svelte
<script lang="ts">
	import Bounded from "$lib/components/Bounded.svelte"
	import PrismicRichText from "$lib/components/PrismicRichText.svelte"
	import type { Content } from "@prismicio/client"
	import * as prismic from "@prismicio/client"
	import CenteredTextParagraph from "./CenteredTextParagraph.svelte"
	import CenteredTextHeading from "./CenteredTextHeading.svelte"

	export let slice: Content.CenteredTextSlice
</script>

<Bounded
	data-slice-type={slice.slice_type}
	data-slice-variation={slice.variation}
	class="relative bg-white py-10 lg:py-20"
>
	{#if prismic.isFilled.richText(slice.primary.text)}
		<div class="max-w-2xl mx-auto text-center">
			<PrismicRichText
				field={slice.primary.text}
				components={{
					heading4: CenteredTextHeading,
					paragraph: CenteredTextParagraph
				}}
			/>
		</div>
	{/if}
</Bounded>
