// src/lib/slices/CallToAction/index.svelte
<script lang="ts">
	import Bounded from "$lib/components/Bounded.svelte"
	import PrismicRichText from "$lib/components/PrismicRichText.svelte"
	import type { Content } from "@prismicio/client"
	import * as prismic from "@prismicio/client"
	import * as typo from "$lib/typography"
	import CallToActionParagraph from "./CallToActionParagraph.svelte"
	import CallToActionHeading from "./CallToActionHeading.svelte"

	export let slice: Content.CallToActionSlice

	const heading = prismic.asText(slice.primary.heading)
	const subheading = prismic.asText(slice.primary.subheading)
</script>

<Bounded
	data-slice-type={slice.slice_type}
	data-slice-variation={slice.variation}
	class="relative bg-white py-10 lg:py-20"
>
	<div class="grid gap-y-8 md:grid-cols-6 md:gap-y-0 md:gap-x-6">
		<div class="space-y-5 md:col-span-2">
			{#if subheading}
				<p class={typo.sansCaps}>{subheading}</p>
			{/if}

			{#if heading}
				<h2 class={typo.serifHeading}>{heading}</h2>
			{/if}
		</div>

		{#if prismic.isFilled.richText(slice.primary.text)}
			<div class="md:col-span-4 md:pl-20">
				<PrismicRichText
					field={slice.primary.text}
					components={{
						paragraph: CallToActionParagraph,
						heading5: CallToActionHeading
					}}
				/>
			</div>
		{/if}
	</div>
</Bounded>

// src/slices/CallToAction.tsx
import * as React from 'react'
import clsx from 'clsx'
import { graphql } from 'gatsby'

import { BoundedBox } from '../components/BoundedBox'
import { sansCaps, serifHeading } from '../typography'
import { HTMLContent } from '../components/HTMLContent'
import type { SliceComponentProps } from '@prismicio/react'

type Slice = Queries.CallToActionFragment & {
	slice_type: 'call_to_action'
}
type Props = SliceComponentProps<Slice>

const CallToAction = ({ slice }: Props) => {
	const heading = slice.primary.heading.text
	const subheading = slice.primary.subheading.text
	const textHTML = slice.primary.text.html

	return (
		<BoundedBox
			as="section"
			data-page-cta
			className={clsx('relative bg-white', 'py-10 lg:py-20')}
		>
			<div className="grid gap-y-8 md:grid-cols-6 md:gap-y-0 md:gap-x-6">
				<div className="space-y-5 md:col-span-2">
					{subheading && <h4 className={sansCaps}>{subheading}</h4>}
					{heading && <h2 className={serifHeading}>{heading}</h2>}
				</div>

				{textHTML && (
					<HTMLContent
						variant="callToAction"
						html={textHTML}
						className="md:col-span-4 md:pl-20"
					/>
				)}
			</div>
		</BoundedBox>
	)
}

export default CallToAction

export const fragment = graphql`
	fragment CallToAction on PrismicPageDataBodyCallToAction {
		id
		primary {
			heading {
				text
			}
			subheading {
				text
			}
			text {
				html
			}
		}
	}
`
